### ISSUE TITLE
discussion: expose buffered records thresold and timeout

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-queue#139]
Opening this issue for a potential discussion after some issues discovered in https://github.com/elastic/apm-queue/pull/116

We currently have no control on records buffering. The kafka producer has options to control the feature (maxbufferedrecords and producer linger) but they are not currently exposed in the library.

Should they be exposed ? Should we treat buffering as an implementation detail ? 

https://pkg.go.dev/github.com/twmb/franz-go@v1.13.3/pkg/kgo#ProducerLinger
https://pkg.go.dev/github.com/twmb/franz-go@v1.13.3/pkg/kgo#MaxBufferedRecords
https://pkg.go.dev/github.com/twmb/franz-go@v1.13.3/pkg/kgo#ManualFlushing

**Comment by kruskall** [comment]
I've updated the title as the issue also applies to pubsub with similar options

**Comment by marclop** [comment]
This may come into play when we start looking at #84.
