### ISSUE TITLE
consistent behaviour on shutdown

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-queue#147]
The two providers have different behaviours on shutdown 

Add a test to ensure the behaviour is consistent

**Comment by kruskall** [comment]
Test discovered another issue with the consumer:

PubSub returns no error on shutdown both when canceling the ctx and when closing the consumer.
Kafka returns an error in both cases.

I'm not sure what we want to do here.

Returning no errors when closing and `context.Canceled` when canceling the context makes sense, on the other hand `net/http` returns an error when closing the server (`ErrServerClosed`). Do we want to apply the same pattern ?

cc @marclop

**Comment by kruskall** [comment]
See https://github.com/elastic/apm-queue/blob/505ba97296dab8e035ee57cc77240e4a5e2fef43/systemtest/produce_consume_basic_test.go#L291

**Comment by marclop** [comment]
@kruskall I think we could likely not return an error if the context has been cancelled or if the deadline exceeded.
