### ISSUE TITLE
Investigate slow systemtest

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-queue#149]
This seems to vary between team members as we are having different experience with test time.

**Comment by kruskall** [comment]
Current test time is at 1283s for me.

A strange thing I noticed is that the pubsub tests take significantly more time than kafka. Not sure if that's intended, for example:

```
PASS: TestShutdown/Kafka/ctx (6.16s)
PASS: TestShutdown/PubSubLite/ctx (65.11s)
```

**Comment by marclop** [comment]
The system test take ~800s on my machine now when running with a GCP region that is close to where my machine is. @kruskall did you notice an improvement by switching to a region closer to you?

**Comment by kruskall** [comment]
I'll run the test again and verify :+1: 

Thanks for the ping!

**Comment by marclop** [comment]
@kruskall After #213 the system test now take ~500s on my machine, and ~600s in CI. Did you have the chance to re-run the system test locally and see how fast (or slow) they are for you?

**Comment by kruskall** [comment]
504s on my machine, I think the situation improved enough compared to what it was.

Thanks for the help! :bow:
