### ISSUE TITLE
system tests: cleanup

### ISSUE THREAD

**Issue by reakaleek** [elastic/apm-queue#169]
## Details

During the implementation of https://github.com/elastic/apm-queue/issues/95 I noticed that the destroying of the terraform resources does not happen on `SIGINT`.

```shell
cd systemtest
go test -v -timeout=30m .
# Ctrl+C
```

## Goal

Destroy terraform resources when the test suite is interrupted.

**Comment by reakaleek** [comment]
@marclop I would need your help here. To be sure resources are destroyed if a workflow is canceled for any reason.

**Comment by axw** [comment]
Do you think we could do this in a followup, when I adapt https://github.com/elastic/apm-queue/pull/172? We won't be using Terraform then, so the approach will likely change.

**Comment by axw** [comment]
I've got a fix for this in https://github.com/elastic/apm-queue/pull/193. What I've done is added a flag to the tests that just destroys resources without running the tests; this is run after running tests, unconditionally, to clean up in case the test process aborted.
