### ISSUE TITLE
Introduce `namespace` concept

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#224]
## Description

Some of the resources created by the topic / reservation manager use a prefix, which allows us to "namespace" these resources. The problem with this approach is that when metrics are produced for the prefixed resources, it make it increasingly more difficult to group by name when they are namespaces with a prefix.

Instead of using the prefixed names in the metrics, it would be better if a "namespace" dimension was used to help group the same resource names.

**Comment by simitt** [comment]
@marclop the goal of this task is to remove  the `namespace` from a metric name and instead set it as dimension on the metric document, right?
Is it clear how the prefix can be identified?

**Comment by marclop** [comment]
Correct that's the overall goal. The specifics are a bit unclear at the moment, but we'll probably need to surface it as a field in the configuration structs and propagate it down to the metrics.
