### ISSUE TITLE
Graceful reloading/reauthentication on credentials rotation

### ISSUE THREAD

**Issue by axw** [elastic/apm-queue#236]
Ensure that both the kafka and pubsublite code gracefully handles credentials changes.

Related: https://github.com/elastic/apm-queue/issues/234 https://github.com/elastic/apm-queue/issues/235

**Comment by axw** [comment]
At least in theory, the seed brokers list could change over time too. e.g. if migrating to a different Azure Event Hubs namespace. This can be achieved by calling kgo.Client.UpdateSeedBrokers.

**Comment by axw** [comment]
For Kafka, I'm thinking of writing a kgo hook that will periodically load a file from disk, extracting select properties defined at https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md (namely `bootstrap.servers` and `sasl.{username,password}`), compare them to the last loaded values, and reconfigure the client if they have changed.

**Comment by simitt** [comment]
@axw is the kafka part done with https://github.com/elastic/apm-queue/pull/241?

I think it would be best to re-focus this issue on `aws` and create a dedicated one for the work in `azure` EventHubs.

**Comment by axw** [comment]
@simitt that PR handles both Kafka and Event Hubs. I don't think I tested Pub/Sub Lite reloading yet, so that would need a new issue.

**Comment by simitt** [comment]
The part that is left to do here is updating each of the services to load the config from a file. @lahsivjar pointed out that https://github.com/knadh/koanf#reading-config-from-files might be a good choice.

**Comment by axw** [comment]
Still need to verify GCP, will come back to that later.
