### ISSUE TITLE
kafka(consumer): Consider processing multiple events

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#243]
## Description

`kafka.partitionConsumer.consume`, ranges over a channel of `[].kgo.Record`, then ranges over each of the `kgo.Record`, translates each of the `kgo.Record` into an `apmqueue.Record` and calls `processor.Process(processCtx, record)` for each of the records.

https://github.com/elastic/apm-queue/blob/c9b9cb1dfd68e23927fedbaf6636f8dc62d37f6c/kafka/consumer.go#L457-L465

Any processor that has a mutex or any synchronisation primitives would benefit from receiving a single call with a list of `apmqueue.Record`, rather than individual calls.

## Advantages

- Decreased contention on sync primitives for processors that require it.
- More predictable behaviour based on the `apmqueue.Processor` API.

## Disadvantages

- Increased memory usage (Could be mitigated by reusing slices using a `sync.Pool`)

**Comment by simitt** [comment]
Based on recent benchmarks it doesn't look like this is necessarily the bottleneck, so deprioritizing this for 2-3 iterations.

**Comment by axw** [comment]
This also conflicts with https://github.com/elastic/apm-queue/issues/277, so we'd need to decide which one to implement.
