### ISSUE TITLE
Update Kafka producer metric names

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#251]
## Description

Create a new metric that encompasses the count of messages produced and use a dimension to report the produce outcome. The new metric name must be `producer.messages.count` and use two dimensions, `outcome=success` and `outcome=failure` to report whether a record was produced or not.

Remove the two metrics below since the new metric will cover both outcomes.

https://github.com/elastic/apm-queue/blob/63f6f01bf68a76aad5fd2f7bd44af0f7519f8e16/kafka/metrics.go#L39-L40

**Comment by endorama** [comment]
The relevant PR in apm-queue has been merged. I'll proceed in updating the related dashboards and alerts.

**Comment by endorama** [comment]
Dashboards PR merged for all environments. Waiting to confirm the sync process worked correctly.

**Comment by endorama** [comment]
Dashboard updates confirmed in staging and production. Closing.

@marclop @kyungeunni I noticed there are some cloned dashboard with the fixes applied, I think they can be removed now.
