### ISSUE TITLE
test: broken `TestProducerMetrics`

### ISSUE THREAD

**Issue by kyungeunni** [elastic/apm-queue#483]
While working on #478, I noticed that the test case `TestProducerMetrics` isn't validating anything, even specifying non-existing metric name as an expected metric, it passes.

For example, 
This test case passes:
https://github.com/elastic/apm-queue/blob/89aef429e73b767c9c58d3e3537d27c2eeefaafc/kafka/metrics_test.go#L207-L209

even though the expected unit is "Byte":
https://github.com/elastic/apm-queue/blob/89aef429e73b767c9c58d3e3537d27c2eeefaafc/kafka/metrics.go#L224-L226

Tried to fix this while working the PR, but fix to the tests cascaded other tests to fail so it seems like it requires dedicated time to fix.

**Comment by 1pkg** [comment]
I think this issue could be partially related to another broken test `TestConsumerMetrics` that I fixed in https://github.com/elastic/apm-queue/pull/579. I will take another look at `TestProducerMetrics` as well to fix it too.
