### ISSUE TITLE
pubsublite(producer): Recover from publish errors

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#61]
## Code

https://github.com/elastic/apm-queue/blob/50c8a56e415494d6117ff470449094ec8715736d/pubsublite/producer.go#L229-L246

**Comment by simitt** [comment]
@marclop do you have an estimation how hard it would be to automatically re-create the producer?

**Comment by marclop** [comment]
I think it's a medium effort task, it requires that:

- We identify the errors that are terminal and require the producer to be recreated.
- Log a message signalling what's about to happen.
  - (Perhaps we could also record a metric, I'm not sure it's worth for now, perhaps that could be an enhancement itself).
- Acquire the producer write lock.
- Close all producers.
- Release the producer lock

After that's done, incoming messages will re-create a producer per topic.
