### ISSUE TITLE
system tests: group consuming

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#94]
## Description

Group consuming must be tested to ensure that records are consumed based on the [`apmqueue.DeliveryType`](https://pkg.go.dev/github.com/elastic/apm-queue#DeliveryType).

```[tasklist]
### Tasks
- [ ] Verify consumption of N records for `AtMostOnceDelivery`.
- [ ] Verify consumption for N records for `AtLeastOnceDelivery`.
```

## Related issues

Depends on #92

**Comment by simitt** [comment]
moved to `ms-04`

**Comment by kruskall** [comment]
PR merged
