### ISSUE TITLE
system tests: Run as part of PR checks

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#95]
## Description

We MUST ensure that merged PRs do not break the system tests, and that these are run for each PR and are required to pass before PRs are merged.

Since the system tests will provision external infrastructure, only PRs opened by approved contributors will run these automatically.

## Related issues

Requires #92

**Comment by simitt** [comment]
@elastic/observablt-robots can you take this task on?

**Comment by cachedout** [comment]
@simitt Yes of course. I've added this to the iteration taking place between May 18 and June 7 which should give you plenty of headroom for 8.9.

@v1v Could you find an owner for this please?

**Comment by v1v** [comment]
> @v1v Could you find an owner for this please?

Sure, @reakaleek is assigned. We have planned this task to happen in this upcoming iteration (`Iteration 22` which starts in 2 days and last for 3 weeks)

**Comment by reakaleek** [comment]
Cool. Thank you!

**Comment by reakaleek** [comment]
Hey @marclop 

I just tried this with 

```shell
go version
go version go1.20.4 darwin/arm64
```

which results in:

```shell
go run -v -timeout=30m .
flag provided but not defined: -timeout
usage: go run [build flags] [-exec xprog] package [arguments...]
Run 'go help run' for details.
```

when I omit the `-timeout` argument, I get this:

```
go run -v .             
package github.com/elastic/apm-queue/systemtest is not a main package
```

Sorry, I'm not too familiar with go. No clue on how to make this run.

**Comment by marclop** [comment]
@reakaleek Oops, sorry. I miss typed. The right command is `go test`.

**Comment by reakaleek** [comment]
@marclop I've got to a point where the `helm_release` resources are installed correctly by terraform.

however, the `kafkatopic` is never becomes `Ready=True` and then the command times out.

```
k get kafkatopics
NAME                                                                                               CLUSTER   PARTITIONS   REPLICATION FACTOR   READY
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a                                        kafka     50           1                    True
dummy.gdvjnzso                                                                                     kafka     1            1                    
strimzi-store-topic---effb8e3e057afce1ecf67c3f5d8e4e3ff177fc55                                     kafka     1            1                    True
strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b   kafka     1            1                    True
```

do you maybe have an idea why this is the behaviour?

**Comment by axw** [comment]
A few alternatives:
 - I'll soon be introducing changes that mean topics are not created by Strimzi, but will be created by the tests directly by using the Kafka protocol. At that point, maybe we don't need Strimzi, and could use a simpler Kubernetes manifest to run a single Kafka broker?
 - Perhaps we could use [Redpanda](https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/kubernetes/local-guide/), which I believe doesn't require any special privileges by default
 - If testing Kafka in Kubernetes proves too difficult, perhaps we could use AWS MSK Serverless

**Comment by reakaleek** [comment]
During the implementation I noticed that terraform resources are not destroyed when the test is interrupted.

I would need your help in this. I created https://github.com/elastic/apm-queue/issues/169.

Thanks!

**Comment by reakaleek** [comment]
@marclop 

We have a problem that I was not thinking of since I started this issue.

This workflow needs access to secrets to provision the resources. However, we don't have access to secrets in a fork PR.
The only way to access secrets is from a PR with the same origin or on the main branch.

Is it okay if we only run this on pushes to main?

Otherwise, we need to come up with a way on how to trigger test system tests and only allow a repo maintainer to be the actor.

**Comment by reakaleek** [comment]
PR:
- https://github.com/elastic/apm-queue/pull/170

**Comment by reakaleek** [comment]
Nevermind, I just read through https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks and in elastic/apm-queue this setting is set to "Require approval for all outside collaborators".

Hence, the PR won't be triggered unless it is approved by a maintainer.

**Comment by reakaleek** [comment]
@marclop I was wrong. Fork PRs don't have access to secrets no matter what. Even if it's approved.

For the time beeing  we can only run this on `main`. 

Let me draft an RFC, I have an idea on how we can still achieve this.

**Comment by reakaleek** [comment]
Reopening:

because after merging there was only 1 successful run on the main branch

https://github.com/elastic/apm-queue/actions/runs/5174903882

All other runs on PRs are failing with 

```
Error: create: failed to create: namespaces "apm-queue-system-test-gh-workflow-run-5176440275-1" not found)

```

or

```
2023-06-05T09:10:51.028Z	ERROR	systemtest/main_test.go:56	failed to provision kafka: failed to run terraform apply: exit status 1
```
