### ISSUE TITLE
health checks should accept a context

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-queue#96]
Found while working on unit testing:

Current methods for health checking use `context.Background` under the hood. 
Since this is usually started by network requests, we should pass a context for proper cancellation:

https://github.com/elastic/apm-queue/blob/9717da3b23c43117048d9644b3d59126e25465a7/kafka/consumer.go#L267-L272

**Comment by marclop** [comment]
Sounds good. We should also update the `apmqueue` package interfaces when we do this:

https://github.com/elastic/apm-queue/blob/9717da3b23c43117048d9644b3d59126e25465a7/queue.go#L42-L59
